DROP DATABASE lab1;
CREATE DATABASE lab1;
DROP TABLE users;
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    firstname VARCHAR(50),
    lastname VARCHAR(50)
);
ALTER TABLE users
ADD COLUMN isadmin INTEGER;
ALTER TABLE users
ALTER COLUMN isadmin TYPE BOOLEAN
USING isadmin::BOOLEAN;
ALTER TABLE users
ALTER COLUMN isadmin SET DEFAULT FALSE;
CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    user_id INTEGER
);
DROP TABLE IF EXISTS tasks;
DROP DATABASE IF EXISTS lab1;
